### PR TITLE
Add locale awareness

### PR DESCRIPTION
**Pull request by mark-careplanner**
Adds locale awareness to Faker factory method instantiation call.

### CODE REVIEW

**Comment by Warxcell** [comment]
I wouldn't do it like that. It's ugly to use $_SERVER variables either it's a standart variable. And language cannot be changed per column basis. 

```
   private static $generators = [];

   private function getGenerator($locale = null) {
      if($locale === null) {
          return self::$generator;
      }
      if(!isset(self::$generators[$locale])) {
          self::$generators[$locale] = Factory::create($locale);
      }
     retirm self::$generators[$locale];
   }

   public function getValue($expression)
    {
        $locale = isset($expression['locale']) ? $expression['locale'] : null;
        return self::getGenerator($locale)->format(self::$formatterTansformerMap[$expression['formatter']]);
    }
```

And if possible somehow to pass the variable through the constructor for default generator.

**Comment by mark-careplanner** [comment]
Understood. How would you recommend getting hold of the locale variable if we don't use $_SERVER?

**Comment by Warxcell** [comment]
In the example I gave - you can pass the locale within the configuration of columns. If you don't pass - it will use english.


```
"table": {
    "telephone": {"formatter":"phoneNumber", "locale": "en"}
}
```

**Comment by mark-careplanner** [comment]
That's a good suggestion. The only trouble is I think you've proposed this fix against your forked version, not the base version, correct? What is happening with maintenance of this project now? Do you have merge permissions?

**Comment by Warxcell** [comment]
Nope. I will soon release my own fork built around symfony (but can be used standalone also). It already includes locale-awareness.

**Comment by mark-careplanner** [comment]
Ah! Exciting! I will check out your version - let me know when it goes live!

**Comment by Warxcell** [comment]
@mark-careplanner you can test it now : https://github.com/Warxcell/gdpr-mysqldump

**Pull request closed without merging**
